//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_Airport
    {
        public int ID { get; set; }
        public string AIRPORT_IATA { get; set; }
        public string AIRPORT_ICAO { get; set; }
        public string SHORT_NAME { get; set; }
        public string CITY_IATA { get; set; }
        public string DORI { get; set; }
        public string NAME_CHINESE { get; set; }
        public string NAME_ENGLISH { get; set; }
        public string FLG_DELETED { get; set; }
        public string REGION_CODE { get; set; }
    }
}
