//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_Airline
    {
        public int ID { get; set; }
        public string Airline_IATA { get; set; }
        public string Airline_ICAO { get; set; }
        public string Short_Name { get; set; }
        public string Host_AirPort_IATA { get; set; }
        public string MaxLogo { get; set; }
        public string MinLogo { get; set; }
        public string DORI { get; set; }
        public string NAME_ENGLISH { get; set; }
        public string NAME_CHINESE { get; set; }
        public string ALLIANCE_CODE { get; set; }
        public string FLG_DELETED { get; set; }
    }
}
