//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_Status
    {
        public int StatusID { get; set; }
        public string Code { get; set; }
        public string CHINESE_NAME { get; set; }
        public string ENGLISH_NAME { get; set; }
        public string Color { get; set; }
        public int StatusLevel { get; set; }
        public string FLG_DELETED { get; set; }
    }
}
