//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CATC_FIDS_DBEntities : DbContext
    {
        public CATC_FIDS_DBEntities()
            : base("name=CATC_FIDS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DailySchedule> DailySchedule { get; set; }
        public virtual DbSet<DailySchedule_Extension> DailySchedule_Extension { get; set; }
        public virtual DbSet<DailySchedule_ExtFileds> DailySchedule_ExtFileds { get; set; }
        public virtual DbSet<EventItem> EventItem { get; set; }
        public virtual DbSet<EventMessage> EventMessage { get; set; }
        public virtual DbSet<F_Aircraft> F_Aircraft { get; set; }
        public virtual DbSet<F_AircraftType> F_AircraftType { get; set; }
        public virtual DbSet<F_Airline> F_Airline { get; set; }
        public virtual DbSet<F_Airline_Sub> F_Airline_Sub { get; set; }
        public virtual DbSet<F_Airport> F_Airport { get; set; }
        public virtual DbSet<F_Alliance> F_Alliance { get; set; }
        public virtual DbSet<F_City> F_City { get; set; }
        public virtual DbSet<F_Country> F_Country { get; set; }
        public virtual DbSet<F_DelayCode> F_DelayCode { get; set; }
        public virtual DbSet<F_Province> F_Province { get; set; }
        public virtual DbSet<F_Status> F_Status { get; set; }
        public virtual DbSet<F_TaskCode> F_TaskCode { get; set; }
        public virtual DbSet<FIDS_Parameter> FIDS_Parameter { get; set; }
        public virtual DbSet<Flight_Dynamic> Flight_Dynamic { get; set; }
        public virtual DbSet<Flight_Schedule> Flight_Schedule { get; set; }
        public virtual DbSet<Flight_Service> Flight_Service { get; set; }
        public virtual DbSet<History_Flight_Dynamic> History_Flight_Dynamic { get; set; }
        public virtual DbSet<L_Operation_Log> L_Operation_Log { get; set; }
        public virtual DbSet<R_DeviceGroup> R_DeviceGroup { get; set; }
        public virtual DbSet<R_DeviceMonitoring> R_DeviceMonitoring { get; set; }
        public virtual DbSet<R_DeviceStatus> R_DeviceStatus { get; set; }
        public virtual DbSet<R_DisplayInfo> R_DisplayInfo { get; set; }
        public virtual DbSet<R_Facility> R_Facility { get; set; }
        public virtual DbSet<R_FacilityType> R_FacilityType { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Sy_Role> Sy_Role { get; set; }
        public virtual DbSet<Sy_UserInfo> Sy_UserInfo { get; set; }
        public virtual DbSet<Sy_UserRole> Sy_UserRole { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Template> Template { get; set; }
        public virtual DbSet<Template_DisplayInfo_Rel> Template_DisplayInfo_Rel { get; set; }
        public virtual DbSet<TemplateDisplayInfoView> TemplateDisplayInfoView { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Flight_Resource_Allocation> Flight_Resource_Allocation { get; set; }
    }
}
