//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Dynamic
    {
        public int FDID { get; set; }
        public int ID { get; set; }
        public string FLG_IDU { get; set; }
        public Nullable<System.DateTime> OPERATION_DATE { get; set; }
        public string FLIGHT_NO { get; set; }
        public string AORD { get; set; }
        public string DORI { get; set; }
        public string TASK_CODE { get; set; }
        public string TERMINAL_NO { get; set; }
        public string AIRLINE_IATA { get; set; }
        public string AIRCRAFT_TYPE_IATA { get; set; }
        public string AC_REG_NO { get; set; }
        public string SERVICE_CLASS { get; set; }
        public string FLG_VIP { get; set; }
        public string ORIGIN_AIRPORT_IATA { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public Nullable<System.DateTime> ATD { get; set; }
        public string DEST_AIRPORT_IATA { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public Nullable<System.DateTime> ATA { get; set; }
        public string PREVIOUS_FLIGHT { get; set; }
        public string NEXT_FLIGHT { get; set; }
        public string ABNORMAL_STATUS { get; set; }
        public string AIRPORT1 { get; set; }
        public string DORI1 { get; set; }
        public Nullable<System.DateTime> STD1 { get; set; }
        public string AIRPORT2 { get; set; }
        public string DORI2 { get; set; }
        public Nullable<System.DateTime> STA2 { get; set; }
        public Nullable<System.DateTime> STD2 { get; set; }
        public string AIRPORT3 { get; set; }
        public string DORI3 { get; set; }
        public Nullable<System.DateTime> STA3 { get; set; }
        public Nullable<System.DateTime> STD3 { get; set; }
        public string AIRPORT4 { get; set; }
        public string DORI4 { get; set; }
        public Nullable<System.DateTime> STA4 { get; set; }
        public string CODE_SHARE1 { get; set; }
        public string CODE_SHARE2 { get; set; }
        public string CODE_SHARE3 { get; set; }
        public string CODE_SHARE4 { get; set; }
        public int ADD_TYPE { get; set; }
        public string Status_Code { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
