//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Service
    {
        public long ID { get; set; }
        public System.DateTime OPERATION_DATE { get; set; }
        public string FLIGHT_NO { get; set; }
        public string AORD { get; set; }
        public long SCHED_ID { get; set; }
        public string SERVICE_NO { get; set; }
        public string SERVICE_NAME { get; set; }
        public Nullable<System.DateTime> SCHED_START_TIME { get; set; }
        public Nullable<System.DateTime> SCHED_END_TIME { get; set; }
        public Nullable<System.DateTime> EST_START_TIME { get; set; }
        public Nullable<System.DateTime> EST_END_TIME { get; set; }
        public Nullable<System.DateTime> ACTUAL_START_TIME { get; set; }
        public Nullable<System.DateTime> ACTUAL_END_TIME { get; set; }
        public string FROM_DEVICE { get; set; }
    }
}
