//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_Resource_Allocation
    {
        public int FRID { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> OPERATION_DATE { get; set; }
        public Nullable<int> FacilityType { get; set; }
        public string FLIGHT_NO { get; set; }
        public string AORD { get; set; }
        public Nullable<int> SCHED_ID { get; set; }
        public Nullable<System.DateTime> SCHED_START { get; set; }
        public Nullable<System.DateTime> SCHED_END { get; set; }
        public Nullable<int> ESTIMATE_ID { get; set; }
        public Nullable<System.DateTime> ESTIMATE_START { get; set; }
        public Nullable<System.DateTime> ESTIMATE_END { get; set; }
        public Nullable<int> ACTUAL_ID { get; set; }
        public Nullable<System.DateTime> ACTUAL_START { get; set; }
        public Nullable<System.DateTime> ACTUAL_END { get; set; }
    
        public virtual R_Facility R_Facility { get; set; }
        public virtual R_Facility R_Facility1 { get; set; }
        public virtual R_Facility R_Facility2 { get; set; }
    }
}
