//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Operation_Log
    {
        public long ID { get; set; }
        public System.DateTime LogTime { get; set; }
        public int LogType { get; set; }
        public int UserID { get; set; }
        public string Stataus { get; set; }
        public int ModuleType { get; set; }
        public string ModuleValue { get; set; }
        public int LogLevel { get; set; }
        public string Remarks { get; set; }
    }
}
