//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R_Facility()
        {
            this.Flight_Resource_Allocation = new HashSet<Flight_Resource_Allocation>();
            this.Flight_Resource_Allocation1 = new HashSet<Flight_Resource_Allocation>();
            this.Flight_Resource_Allocation2 = new HashSet<Flight_Resource_Allocation>();
        }
    
        public int Facility_ID { get; set; }
        public string Aodb_Facility_ID { get; set; }
        public string Display_Symbol { get; set; }
        public string Terminal_NO { get; set; }
        public string DORI { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Status_Timestamp { get; set; }
        public string Status_Remark { get; set; }
        public Nullable<int> Recorder_ID { get; set; }
        public int FacilityType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Resource_Allocation> Flight_Resource_Allocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Resource_Allocation> Flight_Resource_Allocation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight_Resource_Allocation> Flight_Resource_Allocation2 { get; set; }
    }
}
