//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int scheduleID { get; set; }
        public System.DateTime scheduleTime { get; set; }
        public int flightID { get; set; }
        public int siteID { get; set; }
    }
}
