//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sy_Role
    {
        public int role_id { get; set; }
        public string role_name { get; set; }
        public string role_desc { get; set; }
        public string role_status { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
