//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sy_UserInfo
    {
        public int userID { get; set; }
        public string login_status { get; set; }
        public string login_id { get; set; }
        public string login_password { get; set; }
        public string login_password_wage { get; set; }
        public string login_remark { get; set; }
        public string create_user { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
