//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CATC.FIDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template_DisplayInfo_Rel
    {
        public int ID { get; set; }
        public int TemplateID { get; set; }
        public int DisplayID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Weeks { get; set; }
        public short IsCover { get; set; }
        public short IsAdvert { get; set; }
        public string AdvertUrl { get; set; }
        public short Sort { get; set; }
        public System.DateTime SpaceStartTime { get; set; }
        public System.DateTime SpaceEndTime { get; set; }
        public int IntervalSecond { get; set; }
        public int Index { get; set; }
        public string PageName { get; set; }
        public int TopScreenCode { get; set; }
        public int Count { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string DataValue { get; set; }
        public Nullable<int> IsSend { get; set; }
    }
}
